apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echo-ingress
spec:
  rules:
  - host: host.example.com
    http:
      paths:
      - backend:
          serviceName: echo-service
          servicePort: 4080
